#
# /ematrap - информация о выдаче предметов.
#
# Права:
# ematrap.admin - право для админ команд
#
# Перевод всех сообщений в messages.yml

random:
  obsidian: 69 # Шанс рандома обсидиана

# Чтобы в определенных регионах не работали трапки поставьте флаг в worldguard /rg flag <регион> ematrap-use deny/allow
# DENY - отключить трапки в регионе || ALLOW - разрешить трапки в регионе